INSERT INTO PSI_CODIGOS (CODIGO, DESCRIPCION, IDSISTEMA, TIPO) VALUES ('fuentes1', 'Fuentes 1', 'INFO33', 'LAB');
INSERT INTO PSI_CODIGOS (CODIGO, DESCRIPCION, IDSISTEMA, TIPO) VALUES ('fuentes2', 'Fuentes 2', 'INFO33', 'LAB');
INSERT INTO PSI_CODIGOS (CODIGO, DESCRIPCION, IDSISTEMA, TIPO) VALUES ('fuentes3', 'Fuentes 3', 'INFO33', 'LAB');
INSERT INTO PSI_CODIGOS (CODIGO, DESCRIPCION, IDSISTEMA, TIPO) VALUES ('fuentes4', 'Fuentes 4', 'INFO33', 'LAB');
INSERT INTO PSI_CODIGOS (CODIGO, DESCRIPCION, IDSISTEMA, TIPO) VALUES ('562323', 'Colesterol', 'INFO33', 'LAB');
INSERT INTO PSI_CODIGOS (CODIGO, DESCRIPCION, IDSISTEMA, TIPO) VALUES ('68989', 'LDL', 'INFO33', 'LAB');